language: cpp
compiler: gcc
dist: trusty

install:
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

script: 
  - qmake libCalcScripting.pro "CONFIG+=release" "CONFIG+=qtquickcompiler"
#  - qmake -qt=qt5
#  - make
  - make qmake_all
#  - ./travis_qmake_gcc_cpp11_qt5
  - ls -al